### ISSUE TITLE
optomize page

### ISSUE THREAD

**Issue by SirLich** [SirLich/bedrock-harvester#4]
A few required updates:
 - the TOC generation can be removed, since the wiki now has a custom TOC (maybe make this an option?)
 - Remove the duplicates. Somehow. This mostly effects things like `variant` or whatever.

**Comment by Nusiq** [comment]
You can compare dictionaries with `==` in python. Or even check if they are on a list with `in` so you can just avoid adding duplicated components by checking if they're on the list.
```Py
if component not in components:
    components.append(component)
```
